### ISSUE TITLE
Customize base URL from environment variable

### ISSUE THREAD

**Issue by fsmaia** [tobli/alto-saxophone#3]
I would like to be able to customize base URL from an environment variable (like `CHROMEDRIVER_BASE_URL`), to solve scenarios that run through a proxy or firewall and can't reach the public web.

If you will I can develop it and send a PR, it's a simple one liner that tries to read it from process.env :)

Thanks!

**Comment by soulgalore** [comment]
Hey @fsmaia sorry I totally missed this, lets merge and release this asap.

**Comment by soulgalore** [comment]
released and see if we can release Browsertime/sitespeed.io later today with the fixes, it will be in about 10 hours.

**Comment by tobli** [comment]
Sorry for being late to this. @fsmaia are you running a local mirror for the chromedriver repo? Would supporting downloading via a proxy (potentially with authentication) be an option for you? I'm a bit worried that overriding the URL will lead to bugs that are hard to track down. Chromedriver is updated fairy often, and it's easy to miss updating the environment variable every time a new version is out. If referring to a mirror is needed I'd like a check at the end of install that the downloaded version (from the mirror) is the same version that would be downloaded from the official repo. Basically the same check that's in the test case.

**Comment by fsmaia** [comment]
In my specific scenario (don't know if it happens very often), the CI (Jenkins) runs in an environment that has controlled access to Internet. To download packages and dependencies we setup Nexus OSS, that have dependencies either uploaded manually or proxied (like npm). In this scenario selecting the package source is vital.

I got a little confused about version handling too. It could be outside base URL and forcing path with latest Chromedriver, although it may be hard to force a directory structure in some cases. In this case, receiving base URL with version as a variable (template/interpolation) could be a valid solution, e.g. `http://my_base_url.com/chromedriver-${version} `. 

If having Chromedriver in the latest version is a requirement, we could do a checksum and in case of difference fail tests and install step. Else we can still send a big deprecation warning in log.
