### ISSUE TITLE
Not an issue: Ty for the wrapper

### ISSUE THREAD

**Issue by tobeorla** [tobli/alto-saxophone#5]
> Why the funny name you ask? Well, there are countless Selenium modules in npm. Keywords and the description for the module allows you to find it anyway, so might as well choose a unique name.

I've been trying to find a chromedriver wrapper for node, but i only find "Selenium" packages.. Until now :)

Close this "issue" once is read.

**Comment by tobli** [comment]
You're welcome! Have a nice day.
/Tobias
